version: "2"
checks:
  file-lines:
    config:
      threshold: 10000
  method-lines:
    config:
      threshold: 10000
plugins:
  csslint:
    enabled: true
    checks:
      adjoining-classes:
        enabled: false
      box-sizing:
        enabled: false
      duplicate-background-images:
        enabled: false
      duplicate-properties:
        enabled: false
      empty-rules:
        enabled: false
      known-properties:
        enabled: false
      important:
        enabled: false
      order-alphabetical:
        enabled: false
      outline-none:
        enabled: false
      overqualified-elements:
        enabled: false
      zero-units:
        enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
      XXX:
        enabled: false
  phpmd:
    enabled: true
    checks:
      CleanCode/MissingImport:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      Naming/LongVariable:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      order-alphabetical:
        enabled: false
exclude_patterns:
- "api_explorer/*"
- "build/*"
- "client/css/converse.css"
- "client/js/libs/*"
- "server/php/libs/vendors/**/*"